# Creation Date: 10/06/2023 07:33 PM EDT
# Last Updated Date: 10/06/2023 08:00 PM EDT
# Author: Joseph Armstrong (armstrongjoseph08@gmail.com)
# File Name: _early_access.py
# Purpose: Houses functions that have yet to be implemented yet for the
####################################################################################################


def about_early_access_functions():
    print(
        "Early Access functions are functions generated by a generator script " +
        "when an API endpoint is created, but not implemented yet by this python package."
    )


# TODO: Create a code generator if a function doesn't exist.
